name: 'Add designer to review'
on:
  workflow_call:

jobs:
  add-designer:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/add_designer_to_review.yml'
