on:
  workflow_call:
    inputs:
      pr_url:
        required: true
        type: string
    outputs: 
      result: 
        description: PR info
        value: ${{ jobs.fetch.outputs.result }}
jobs:
  fetch:
    name: Fetch_PR
    runs-on: ubuntu-latest
    outputs: 
      result: ${{ steps.fetch-pr.outputs.result }}
    steps:
      - name: fetch PR info
        id: fetch-pr
        uses: actions/github-script@v6
        with:
          script: | 
            console.log('${{ inputs }}')
            const result = await github.request('${{ inputs.pr_url }}')
            console.log(result);
            return result.data;
