
name: Label Reviews

on:
  pull_request:
    types: [labeled, unlabeled]
  
jobs:
  require-reviewers:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Require-reviewers
        uses: travelperk/label-requires-reviews-action@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.OWNER_TOKEN }}
