name: pull request review requested notification
on:
  pull_request:
    types: [review_requested]
    branches:
    - main

jobs:
  fetch:
    name: fetch
    uses: ./.github/workflows/fetch_pr_info.yml
    with:
      pr_url: ${{ github.event.pull_request.url }}
      
  reviewers:
    name: check length of reviewers
    runs-on: ubuntu-latest
    needs: fetch
    outputs: 
      result: ${{ steps.reviewers.outputs.result }}
    steps:
      - name: reviewers
        id: reviewers
        uses: actions/github-script@v6
        with:
          script: | 
            const reviewers = ${{ fromJSON(needs.fetch.outputs.result).requested_reviewers[0].login }};
            console.log(reviewers);
              
    

  notify:
    name: notify
    needs: [fetch, reviewers]
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.check.outputs.result).reviewersLength > 2 }}
    steps:
      - name: send telegram message on PR
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            &#128065;&#128065;&#128065;
            PR от ${{ fromJSON(needs.fetch.outputs.result).user.login }}
            
            ${{ fromJSON(needs.fetch.outputs.result).title }}
            
            &#128104;&#128104; требует ревью от ${{ fromJSON(needs.reviewers.outputs.result).lastReviewer.login }}
            
            ${{ fromJSON(needs.fetch.outputs.result).html_url }}
            
