name: pull request review requested notification
on:
  pull_request:
    types: [review_requested]
    branches:
    - main

jobs: 
  reviewers:
    name: check length of reviewers
    runs-on: ubuntu-latest
    outputs: 
      result: ${{ steps.reviewers.outputs.result }}
    steps:
      - name: reviewers
        id: reviewers
        uses: actions/github-script@v6
        with:
          script: | 
            const approvedReviewsResult = await github.request(context.pull_request.url + '/reviews');
            const approvedReviews = approvedReviewsResult.data.filter(review => review.state === 'APPROVED');
            const requestedReviewers =  context.pull_request.requested_reviewers;
            
            return { reviewersLength: reviewers.length + approvedReviewers.length, reviewer: context.requested_reviewer };
              
    

  notify:
    name: notify
    needs: reviewers
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.reviewers.outputs.result).reviewersLength > 2 }}
    steps:
      - name: send telegram message on PR
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            &#128065;&#128065;&#128065;
            PR от ${{ fromJSON(needs.fetch.outputs.result).user.login }}
            
            ${{ fromJSON(needs.fetch.outputs.result).title }}
            
            &#128104;&#128104; требует ревью от ${{ fromJSON(needs.reviewers.outputs.result).reviewer.login }}
            
            ${{ fromJSON(needs.fetch.outputs.result).html_url }}
            
